"""empty message

Revision ID: 837fc6bf612a
Revises: 045d808f6b28
Create Date: 2023-12-18 22:10:27.566998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837fc6bf612a'
down_revision = '045d808f6b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_climate_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.create_unique_constraint('planet_climate_key', ['climate'])

    # ### end Alembic commands ###
