"""empty message

Revision ID: 872bbd5bc62c
Revises: 3b29c23076b5
Create Date: 2023-12-18 23:31:45.040845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872bbd5bc62c'
down_revision = '3b29c23076b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoriteplanets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoriteplanets')
    # ### end Alembic commands ###
